name: POI (.NET) Build and Test

on:
  push:
    branches: [ main ]
    paths: apis/poi
  pull_request:
    branches: [ main ]
    paths: apis/poi
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: apis/poi
    - name: Build
      run: dotnet build --no-restore
      working-directory: apis/poi
    - name: Test
      run: dotnet test apis/poi/tests/UnitTests/UnitTests.csproj --no-build --verbosity normal
    - name: Create An Issue
      if: ${{ failure() }}
      uses: JasonEtco/create-an-issue@v2.6.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ISSUE_TITLE: 'Issue auto created for POI build'
        GITHUB_ISSUE_BODY: 'Check your failed POI build'
      with:
        filename: .github/ISSUE_TEMPLATE_chu.md
        
  docker_push:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:  
    - name: Docker Images Build And Push
    # You may pin to the exact commit or the version.
    # uses: risfeng/docker-image-build-push-action@cb2810d0b48aeef5fec933dee19b595319c80e1d
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_ENDPOINT }} # default: index.docker.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build apis/poi/web -t ${{ secrets.ACR_ENDPOINT }}/devopsoh/api-poi:${{github.run_number}}
        docker push ${{ secrets.ACR_ENDPOINT }}/devopsoh/api-poi:${{github.run_number}}
    
    - name: Create An Issue
      if: ${{ failure() }}
      uses: JasonEtco/create-an-issue@v2.6.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/ISSUE_TEMPLATE_chu.md
