name: .NET

on:
  push:
    branches: [ main, chu-chen-branch ]
  pull_request:
    branches: [ main, chu-chen-branch ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: apis/poi
    - name: Build
      run: dotnet build --no-restore
      working-directory: apis/poi
    - name: Create issue on build failure
      if: ${{ failure() }}
      uses: JasonEtco/create-an-issue@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_COMMIT_SHA: ${{ github.sha }}
          GITHUB_REPO_OWNER: 'chu-chen'
          GITHUB_REPO_NAME: 'myrepo'
          GITHUB_ISSUE_TITLE: 'Issue auto created'
          GITHUB_ISSUE_BODY: 'Check your failed build'  
    - name: Test
      run: dotnet test apis/poi/tests/UnitTests/UnitTests.csproj --no-build --verbosity normal
