name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: apis/poi
    - name: Build
      run: dotnet build --no-restore
      working-directory: apis/poi/web
    - name: Test
      run: dotnet test apis/poi/tests/UnitTests/UnitTests.csproj --no-build --verbosity normal
